apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: '{{ .Chart.Name }}-ingress'
  namespace: '{{ .Values.namespace }}'
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: app
            port:
              number: {{ .Values.service.targetPort }}
        path: /
        pathType: ImplementationSpecific
