apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-service-monitor
  labels:
    component: backend
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      name: {{ .Chart.Name }}
  endpoints:
  - interval: 30s
    targetPort: 8080
    scheme: http
    path: /metrics